{% set name = "yabadaba" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7bbe60bac4828568a0c7c93162a77248256165a06223768621bd58c8668654a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - lxml
    - datamodeldict
    - ipython
    - numpy
    - pandas
    - cdcs >=0.2.1
    - pymongo
    - tqdm

test:
  imports:
    - yabadaba
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/yabadaba
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: An abstraction layer for NoSQL databases
  description: |
    Yay, a base database! An abstraction layer allowing for common interactions
    with Mongo, CDCS and local directory databases and records.
  doc_url: https://github.com/usnistgov/yabadaba
  dev_url: https://github.com/lmale99/yabadaba

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
