{% set name = "yabadaba" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd4bc16914c463df83f146d909709761aa158b842808e71c89f3462de08cea26

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml
    - datamodeldict
    - ipython
    - numpy
    - pandas
    - cdcs >=0.2.1
    - pymongo
    - tqdm
    - pillow

test:
  imports:
    - yabadaba
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/yabadaba
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: An abstraction layer for NoSQL databases
  description: |
    Yay, a base database! An abstraction layer allowing for common interactions
    with Mongo, CDCS and local directory databases and records.
  doc_url: https://github.com/usnistgov/yabadaba
  dev_url: https://github.com/lmale99/yabadaba

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
